blank_issues_enabled: true
contact_links:
  - name: Review Open Issues (Mirror 1)
    url: https://github.com/rc-chuah/Windows-Recall-Switch/issues
    about: Please Ensure You Have Gone Through Open Issues.
  - name: Review Open Issues (Mirror 2)
    url: https://github.com/RaynerSec/Windows-Recall-Switch/issues
    about: Please Ensure You Have Gone Through Open Issues.